UniversalRobots/Universal_Robots_ROS_Driver

- ur_robot_driver/resources/servoj.urscript
This solves #26 
When no controller is active, we still send keepalive commands, which made the robot extrapolate the latest motion. Instead, we now send the current position as setpoint.
> When no controller is active, set the current point as setpoint.

- .travis.yml
- ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.h
- ur_controllers/src/speed_scaling_state_controller.cpp
- ur_robot_driver/include/ur_robot_driver/comm/pipeline.h
- ur_robot_driver/include/ur_robot_driver/comm/producer.h
- ur_robot_driver/include/ur_robot_driver/rtde/rtde_client.h
- ur_robot_driver/include/ur_robot_driver/ur/ur_driver.h
- ur_robot_driver/src/comm/tcp_socket.cpp
- ur_robot_driver/src/primary/robot_state/kinematics_info.cpp
- ur_robot_driver/src/ros/hardware_interface.cpp
- ur_robot_driver/src/ros/hardware_interface_node.cpp
- ur_robot_driver/src/rtde/data_package.cpp
- ur_robot_driver/src/rtde/rtde_client.cpp
- ur_robot_driver/src/rtde/rtde_package.cpp
- ur_robot_driver/src/ur/ur_driver.cpp
This MR aims at fixing startup timing issues like
* Too much time goes by between starting the pipeline and starting robot control
* Too much time goes by between the RTDE handshake and starting the pipeline
Also, we added more error handling (of cases that usually should not occur) to the RTDE handshake process.
This should solve #6
> Fix init timing

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/package.xml
I believe this is a left-over from `ur_modern_driver` but is not actually used in the current implementation.
> Remove industrial_msgs dependency.

- ur_calibration/CMakeLists.txt
`libyaml-cpp-dev` on Xenial doesn't export the `yaml::yaml` target yet, and uses a non-standard variable for it's include dirs.
These changes let Catkin properly `DEPEND` on `yaml-cpp` and correctly link to it.
> Fixup yaml-cpp linking and include paths in ur_calibration

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/hardware_interface_plugin.xml
- ur_robot_driver/package.xml
- ur_robot_driver/src/ros/hardware_interface.cpp
We propose the minimum set of changes to use the driver together with [combined_robot_hw](https://github.com/ros-controls/ros_control/tree/melodic-devel/combined_robot_hw).
In our setup we use a haptic device with an UR robot using the `combined_robot_hw` and it works fine. This change doesn't break anything, and even if this is not the final solution, at least someone could use it as we do. 
For example, we see some limitations to how the `combined_robot_hw` together with the driver handles `read` operations. If I'm correct `read` is a blocking operation, and the `combined_robot_hw` executes this operation for all hardwares consecutively. Even if I haven't tested yet, if we combine multiple arms together with with some extra hardware it won't work properly.
There are many things to …
> Support for combined robot hardware

- ur_robot_driver/src/ur/ur_driver.cpp
Otherwise script will not be interpreted by the robot which might be counter-intuitive.
Changing the behavior as such will also be the same as in the ur_modern_driver
so migrating will be easier.
I decided to change the function's interface to copy the string in order add a
trailing '\n' if necessary.
> Always end script commands with a newline

- ur_robot_driver/include/ur_robot_driver/ur/tool_communication.h
It actually had a 0 too much. We use scientific notation to make this more clearly visible in future.
Fixes #52
> Fix faulty 1MBaud rate

- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/include/ur_robot_driver/ros/hardware_interface.h
- ur_robot_driver/include/ur_robot_driver/ur/ur_driver.h
- ur_robot_driver/include/ur_robot_driver/ur/version_information.h
- ur_robot_driver/src/ros/hardware_interface.cpp
- ur_robot_driver/src/ur/ur_driver.cpp
As script code interaction needs some deeper knowledge about the pitfalls of URScript, this MR provides an easy-access service to zero the robot's ftsensor.
Currently, we always advertise the service, I'd like to only advertise it when an e-Series is connected or report `false` when being called on a CB3 robot.
> Added a service to zero the robot's ftsensor

- ur_robot_driver/src/rtde/data_package.cpp
Only concerned initialisation. Name not used elsewhere in ur_robot_driver.
> Fix spelling of "actual_main_voltage"

- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/include/ur_robot_driver/ros/hardware_interface.h
- ur_robot_driver/include/ur_robot_driver/ur/ur_driver.h
- ur_robot_driver/launch/ur10_bringup.launch
- ur_robot_driver/launch/ur10e_bringup.launch
- ur_robot_driver/launch/ur3_bringup.launch
- ur_robot_driver/launch/ur3e_bringup.launch
- ur_robot_driver/launch/ur5_bringup.launch
- ur_robot_driver/launch/ur5e_bringup.launch
- ur_robot_driver/launch/ur_common.launch
- ur_robot_driver/launch/ur_control.launch
- ur_robot_driver/src/ros/hardware_interface.cpp
- ur_robot_driver/src/ur/ur_driver.cpp
Hi. There is a WIP PR to solve issue https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/45.
~~1. What to fill in launch and .h file docstring? There are two new arguments: `reverse_port` and `script_sender_port`. I did not find any documentation with this ports description,~~
resolved
~~2. I used `int` type for ports, but they were `uint32_t`. The reason to use `int` is to get rid of type casting while [getParam](http://docs.ros.org/melodic/api/roscpp/html/classros_1_1NodeHandle.html#aab9a9e869bc87ba474a8661fda5b049f) works with `int`, but not unsigned. Do you think an issue could happen because of it?~~
resolved
> 'reverse_port' and 'script_sender_port' parameters

- ur_robot_driver/src/comm/server.cpp
- ur_robot_driver/src/comm/tcp_socket.cpp
- ur_robot_driver/src/ur/ur_driver.cpp
Sockets do not necessarily have to be in state connected when they should be
closed. Before, only connected sockets got closed leading to a "socket leak"
if a socket was disconnected before a close request was processed.
With this fix all sockets with a valid file descriptor get closed when close()
is being called.
This fixes #91
> Close all closable sockets

- ur_robot_driver/src/ros/robot_state_helper.cpp
When robot is already in the target mode (safety- and robot mode) and the set_mode
action is called with requesting to start the program afterwards, the program
did not start as the robot already was at the desired state.
However, e.g. after a protective stop that is resolved by hand (e.g. when driving
into joint limits) users expected to call that action to restart the robot
again.
With this change, we do the usual check whether to start the program again.
This way, this action can always be used to make sure the robot is running with
the program correctly.
> Always go through updateRobotState function in goal callback

- ur_robot_driver/doc/ROS_INTERFACE.md
The description for the ur3_bringup.launch section uses the term ur5
> Fix typo in ur3_bringup.launch section of ROS_INTERFACE.md

- ur_robot_driver/doc/real_time.md
Adding these items to the real-time patch installation instructions eliminate issues encountered when installing on a clean Ubuntu 18.04 system.
> real_time.md improvements

- controller_stopper/package.xml
- ur_calibration/package.xml
- ur_controllers/package.xml
- ur_dashboard_msgs/package.xml
- ur_robot_driver/package.xml
This reduces ambiguity and facilitates automated parsing and identification of licenses.
Refer to [spdx.org](https://spdx.org) for more information.
> Use SPDX license identifiers

- ur_robot_driver/src/ros/hardware_interface.cpp
Otherwise the joint_state_controller will continue publishing old joint data.
> Require a controller reset when reading data from RTDE fails

- ur_robot_driver/include/ur_robot_driver/ros/hardware_interface.h
- ur_robot_driver/src/ros/hardware_interface.cpp
all control communication was set to false when a switch was called. This
is not correct, as we might e.g. only start a reading controller such as
the FTS measurements.
Second, controllers were never checked for matching joints in this HW interface
which is problematic in combined-hw cases.
This is an extended implementation of the problem raised by @carebare47 inside #109
> Fixes controller switches to only act if necessary

- ur_robot_driver/include/ur_robot_driver/rtde/rtde_client.h
- ur_robot_driver/src/rtde/rtde_client.cpp
Throw an exception if the RTDE handshake could not be established.
This implements #24 
Functionally this should not be changing too much. Before, we would have gotten a `Could not get fresh data package from robot` on an illegal input recipe. 
An illegal output recipe would still have been running, it would just never have been sent to the driver.
> RTDE handshake verification

- ur_robot_driver/src/ros/hardware_interface.cpp
`hardware_interface.cpp` line 703-704 reads two different analog inputs and stores them in the same variable.
> Fix bug overwriting msg_.analog_input2 variable

- README.md
Before, the main badge could get to failure when there was a PR coming in that failed.
> Use badge only from pushes

- ur_robot_driver/src/ur/ur_driver.cpp
replaced ros references that shouldn't be there
We want to keep the pure driver part ros-independent
> Clean ur cpp driver part

- ur_robot_driver/include/ur_robot_driver/ros/robot_state_helper.h
- ur_robot_driver/include/ur_robot_driver/ur/datatypes.h
- ur_robot_driver/src/ros/robot_state_helper.cpp
It can happen that the action gets triggered before the mode callback got triggered which will lead to a crash of the helper. (See #176)
While this changes stops the helper from crashing when this happens, it might
not be the best idea to do so as the question remains, what we should do
if we haven't even received a current status from the robot.
With the changes introduced inside this commit, the helper would trigger the
respective state changes, which might lead to wrong requests if we aren't entirely
sure what to do.
One solution would be to reject goals as long as no status was received,
but that would break such scenarios where you want to activate the robot automatically
during startup.
Another idea would be to delay actually starting the action server until we
received both, robot …
> Initialize member variables

- .clang-format
- .github/workflows/ci.yml
This statement was missing in the clang-format specification. At least with newer clang-format versions this is not being checked properly, otherwise.
> Added case label statement

- ur_robot_driver/launch/ur10_bringup.launch
- ur_robot_driver/launch/ur10e_bringup.launch
- ur_robot_driver/launch/ur3_bringup.launch
- ur_robot_driver/launch/ur3e_bringup.launch
- ur_robot_driver/launch/ur5_bringup.launch
- ur_robot_driver/launch/ur5e_bringup.launch
Note: I haven't tested this (as in: started the driver), but I expect it to work as described.
> robot_driver: use pass_all_args to reduce verbosity

- ur_robot_driver/src/rtde/rtde_client.cpp
I am not completely sure this is correct, but the previous placement looks like a bug
> Fix variable type checking in rtde_client

- ur_robot_driver/CMakeLists.txt
Usage of the driver in a combined_robot_hw requires this change, as there will otherwise be undefined symbols from hardware_interface.cpp.
> Export hardware interface library in CMakeLists

- ur_robot_driver/config/ur10_controllers.yaml
- ur_robot_driver/config/ur10e_controllers.yaml
- ur_robot_driver/config/ur3_controllers.yaml
- ur_robot_driver/config/ur3e_controllers.yaml
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/config/ur5e_controllers.yaml
See the commit comment for some rationale.
Note: the `state_publish_rate` has been left to be equal to the `loop_hz`, as this controls how often the internal (position/velocity/effort) controller of the JTC publishes its state (ie: tracking error, target position, etc). That is something which *should* be published at the same rate the controller is run to actually be useful.
> driver: use default rates for JTC goal monitor rates.

- ur_robot_driver/CMakeLists.txt
Installing the resources folder was missing. Installing it as suggested by @gavanderhoorn in #201 
I was considering only installing the recipe and urscript file and not the complete folder, as this also contains the urcap installation files. My reasoning was that a full installation should also contain those. 
On the other hand users probably won't grab them out of `/opt/ros/distro/share/ur_robot_driver/resources` once there is a binary installation available.
Any opinions on this?
Closes #201
> Install resources directory

- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/include/ur_robot_driver/ros/hardware_interface.h
- ur_robot_driver/src/ros/hardware_interface.cpp
This PR adds a service to setup the active payload through a ROS service. 
This PR depends on https://github.com/ros-industrial/universal_robot/pull/470 being accepted which is why this is a draft PR.
> Added a service to setup the active payload

- .github/dockerursim/build_and_run_docker_ursim.sh
- .github/workflows/ci.yml
- ur_robot_driver/test/driver.test
- ur_robot_driver/test/test_rtde_client.cpp
This Pull-Request contains changes to the network used in Industrial CI pipeline and the static IPs used in the tests.
This Pull-Request moves away from using the default Docker network in the range 172.17.0.0/16, since a specific IP cannot be chosen/guaranteed within this range. Instead, a network is now created with range 192.168.0.0/16, which allows for assigning specific IPs to the containers.
> Changed network in Industrial CI pipeline

- README.md
Instead of using unicode characters directly, use textual emoji names (from [this list](https://github.com/ikatyang/emoji-cheat-sheet#av-symbol)).
This renders more consistently for me in several browsers (Firefox, Edge, etc) on both Windows and Linux (haven't checked OSX).
The previous icons were black (play) and blue (stop) for me, with inconsistent styles.
> readme: improve consistency between play & stop buttons

- ur_robot_driver/config/ur10_controllers.yaml
- ur_robot_driver/config/ur10e_controllers.yaml
- ur_robot_driver/config/ur3_controllers.yaml
- ur_robot_driver/config/ur3e_controllers.yaml
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/config/ur5e_controllers.yaml
- ur_robot_driver/src/ros/hardware_interface.cpp
Modified hardware interface to look for joints parameter under the robot_hw node handle. By doing this, removing the hardware_interface prefixed namespace and just having joints as the parameter name, I have managed to get this working well with both a combined robot hardware interface with 2 arms under the same controller manager and with a single arm as is usual.
Similar to pr #110 but does not require the addition of another param. Does modify the hardware_interface param in the controller yamls to be ur_hardware_interface. But after testing and looking at source it seems only the joints parameter references that name.
> Use Robot_hw_nh node handle for joints.

- ur_robot_driver/test/driver.test
The trajectory test seems to not work anymore since a
couple of weeks. Running those locally (also with a
ursim running inside a docker container) works perfectly
fine, but running it inside the github action not.
As this is blocking many merges currently, I suggest
to disable this temporarily while opening an issue to fix it.
> Disable trajectory test for now

- ur_robot_driver/CMakeLists.txt
This macro works just like the normal `install` macro, but it also automatically changes the shebang line in the python file to `python2` or `python3`, depending which version is used.
See: http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs
What this means is that this package can be used with Python3 without
any further changes, for example in ROS Noetic.
> Use catkin_install_python macro for python files

- ur_calibration/src/calibration_consumer.cpp
- ur_robot_driver/src/hardware_interface.cpp
Inside the driver we want to use plain ROS logging instead of the library's logging macros.
> Replace two logging macros with ROS logging macros.

- ur_calibration/src/calibration_consumer.cpp
- ur_robot_driver/src/hardware_interface.cpp
Inside the driver we want to use plain ROS logging instead of the library's logging macros.
> Replace two logging macros with ROS logging macros. (#330)

- ur_robot_driver/resources/ros_control.urscript
This is actually not properly checked by the driver, as keepalive signals
won't be sent when the program is paused.
When https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/46 will be merged, this line will cause a warning in each control cycle. Without https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/46 merged, this effectively doesn't change anything.
> Remove manual keepalive message from script

- .github/workflows/ci.yml
Since ROS kinetic reached EOL we can remove the tests for kinetic from this repo
Simultaneously, we should add those for noetic, as there are users for noetic
already.
> Replace kinetic with noetic

- ur_robot_driver/src/hardware_interface.cpp
Quaternion() returns 0,0,0,0 which leads to an invalid transform.
> ensure extractToolPose always returns a valid transform

- ur_robot_driver/src/hardware_interface_node.cpp
Reading this from system may end up in undefined behavior. (https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/306)
> Fixes reading has_realtime property

- ur_robot_driver/test/integration_test.py
Before, the test wasn't actually being run.
> rename test method to be actually run by unittest

- README.md
As `ur_msgs` is not yet released for ROS noetic a notice on how to add this to the local workspace is added to the toplevel README file.
This came up in #385 and #384
> Add build notice about ROS noetic

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/config/ur10_controllers.yaml
- ur_robot_driver/config/ur10e_controllers.yaml
- ur_robot_driver/config/ur16e_controllers.yaml
- ur_robot_driver/config/ur3_controllers.yaml
- ur_robot_driver/config/ur3e_controllers.yaml
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/config/ur5e_controllers.yaml
- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/package.xml
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/test/driver.test
- ur_robot_driver/test/integration_test.py
This PR adds Cartesian streaming control and controllers to the driver.
In analogy to the JointPosition and JointVelocity interface, a Pose and Twist interface is added. We have three controllers added as  examples:
- `twist_controller`: publish a cartesian twist to the robot's tcp
- `pose_based_cartesian_traj_controller`: Cartesian trajectory execution using a pose interface
- `joint_based_cartesian_traj_controller`: Cartesian trajectory execution using an IK and a joint position interface
> Cartesian control

- ur_calibration/README.md
The example was referencing the library package where it should have been
referencing the driver package.
Closes #434 
Thanks @AlcatrAAz for spotting this.
> Fix package name in calibration example

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/scripts/test_move
> Fix test move python3

- ur_robot_driver/launch/ur10_bringup.launch
- ur_robot_driver/launch/ur10e_bringup.launch
- ur_robot_driver/launch/ur16e_bringup.launch
- ur_robot_driver/launch/ur3_bringup.launch
- ur_robot_driver/launch/ur3e_bringup.launch
- ur_robot_driver/launch/ur5_bringup.launch
- ur_robot_driver/launch/ur5e_bringup.launch
- ur_robot_driver/launch/ur_common.launch
- ur_robot_driver/launch/ur_control.launch
The UR-robot is only one part of our roslaunch-setup, so I would like to be able to have the rest of the system (non-UR) continue to run even if the ur_hardware_interface-node dies. This is primarily to be able to inspect and collect diagnostics before displaying the appropriate information and available options (most likely restarting ros) to the user.
> Make hw_interface-node required-argument optional

- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/src/hardware_interface.cpp
I've added the ability to change the default topic on which the speed scaling factor is published.
This homogenizes the behavior, considering the wrench topic can currently be renamed. I've been working on a project that involves two UR arms running simultaneously, and it has been useful to maintain separate speed sliders rather than being forced to receive only one robot's slider state. In particular, if the robot which is not publishing state protective stops, I have difficulty stopping its related hardware because I have no programmatic indication of the fault.
Use a ROS Param just like the wrench topic is defined.
I have been using this in my project without any visible side effects.
> Add optional topic rename for speed scaling factor

- ur_robot_driver/scripts/test_move
Otherwise we get an ugly error message that the target controller is already loaded.
> test_move: Load controller only if it is not already loaded

- ur_dashboard_msgs/CMakeLists.txt
- ur_dashboard_msgs/srv/IsInRemoteControl.srv
- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/include/ur_robot_driver/dashboard_client_ros.h
- ur_robot_driver/src/dashboard_client_ros.cpp
This PR adds one of the missing calls, `is in remote control`, from the dashboard server.
This is accessible through `raw request` but I thought it would be better to have it here. I am currently using it to alert the remote operator. Sometimes people forget to set it back to remote mode after the manual operation.
After preparing the pr, I found out there is an issue-#76 raised to implement additional missing calls. @fmauch If you see it reasonable to add the remaining calls, I can prepare separate PRs for them.
> Dashboard service to query whether the robot is in remote control

- README.md
Since https://github.com/ros-industrial/universal_robot/pull/538 is merged, we can now direct users to the upstream repo directly.
> Change README to use the description from ros-industrial/universal_robot

- ur_robot_driver/launch/ur_control.launch
This addresses issue #568, which just allows passing an empty `stopped_controllers` argument in the launch file. This allows one to completely avoid loading controllers which are not used, avoiding clutter in the controller manager.
> Allow empty stopped_controllers argument.

- ur_robot_driver/doc/usage_example.md
Should use [`moveit_planning_execution.launch`](https://github.com/ros-industrial/universal_robot/blob/melodic-devel-staging/ur5e_moveit_config/launch/moveit_planning_execution.launch) as described in [this commit](https://github.com/ros-industrial/universal_robot/commit/c4d07d781a9e1df68375752bb8dc052468e0bfca).
The current command uses `ur5e_moveit_planning_execution.launch`, which results in the following error:
```
RLException: [ur5e_moveit_planning_execution.launch] is neither a launch file in package [ur5e_moveit_config] nor is [ur5e_moveit_config] a launch file name
The traceback for the exception was written to the log file
```
> Fix MoveIt! command in Example

- README.md
`universal_robot` should be cloned to `catkin_ws/src` instead of `catkin_ws`.
The current command clones it to `catkin_ws`, which results in the following error:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ur_robot_driver: Cannot locate rosdep definition for [ur_description]
```
> Fix universal_robot clone destination in BUILDING

- controller_stopper/CMakeLists.txt
- ur_calibration/CMakeLists.txt
- ur_dashboard_msgs/CMakeLists.txt
- ur_robot_driver/CMakeLists.txt
C++14 has been the default for clang and gcc since before Ubuntu 18.04 and enforcing the old standard breaks on systems with a current version of log4cxx (Ubuntu 22.04 +, Arch Linux, Lunar Linux, Debian Testing, ...)
> [ROS-O] Drop old C++ compiler flags

- ur_dashboard_msgs/action/SetMode.action
- ur_robot_driver/src/robot_state_helper.cpp
- ur_robot_driver/test/integration_test.py
This should make the message `SetMode` action easier to interpret. My initial motivation was that the mode itself is documented inside the `RobotMode.msg` file.
> Robot mode in set mode

- README.md
- ur_robot_driver/src/hardware_interface.cpp
Since #566 we increased the minimum required Polyscope version, which we didn't document so far, leading to #599. This adds the required documentation and error output.
> Update minimal required polyscope version in docs

- ur_robot_driver/src/hardware_interface_node.cpp
as discovered in https://github.com/ros-industrial/kuka_experimental/pull/257
> fix typo and use ros logging

- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/launch/ur_common.launch
- ur_robot_driver/launch/ur_control.launch
- ur_robot_driver/scripts/test_move
- ur_robot_driver/src/hardware_interface.cpp
This requires the changes from this [PR](https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/103) in order to work.
> Implemented spline interpolation in joint space

- ur_robot_driver/test/integration_test.py
Otherwise the trajectory points will never be sent.
> Specify velocities for trajectory forwarding test

- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/test/integration_test.py
And integrated it with the tool contact test. This service will obtain the software version of the robot, which can be useful for certain functionalities that only work on e-series robots, for example. This PR depends on [PR](https://github.com/ros-industrial/ur_msgs/pull/24) for functionality and [PR](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/686) for the integration test to work.
> Implemented get version service

- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/src/hardware_interface.cpp
This service allows setting an analog output with an output domain.
This relies on https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/211 and https://github.com/ros-industrial/ur_msgs/pull/28 and fixes #709.
> Add a set_analog_output service

- README.md
Since there is no direct dependency from the driver to the calibration package (It only needs a valid calibration file to work), the calibration package isn't automatically installed with the driver. Hence, we should add it to the installation instructions.
This fixes #727
> Add ur_calibration to installation instructions

- ur_robot_driver/src/hardware_interface.cpp
As they are floating point values, we should not parse them into ints from the parameters.
This fixes #726
> Parse the rx and tx idle chars as floats

- ur_robot_driver/src/hardware_interface.cpp
Everywhere else we state the limits should be [0.0, 1.0] which makes sense.
Closing #737
> Allow setting the speed slider fraction to 0.0 from service

- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/launch/ur_common.launch
- ur_robot_driver/launch/ur_control.launch
- ur_robot_driver/src/hardware_interface.cpp
Backport of ROS2 PR https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/1003
Useful when the connection to the robot does not support real-time control.
If it fixes the issue #507 for me
> Add ROS param (robot_receive_timeout) to control reverse interface timeouts

- ur_robot_driver/src/hardware_interface.cpp
When we raised the version requirements to 3.14/5.9 we didn't update the output in the ROS driver.
> Update the minimum required polyscope version in the output

- ur_robot_driver/src/hardware_interface.cpp
PolyScope X doesn't have the dashboard server, so we should disable starting the dashboard client with the driver there.
This should fix #758
> Start dashboard client in driver only when software version < 10
