- README.md
> readme: remove spurious slash

- README.md
> README.md: typos, consistency

- .travis.yml
- ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.h
- ur_controllers/src/speed_scaling_state_controller.cpp
- ur_robot_driver/src/primary/robot_state/kinematics_info.cpp
- ur_robot_driver/src/ros/hardware_interface.cpp
- ur_robot_driver/src/rtde/data_package.cpp
- ur_robot_driver/src/rtde/rtde_package.cpp
Code formatting and specifying clang-format version to satisfy the CI pipeline
> Formatting

- README.md
Compile-tested in `ros:melodic`. Steps are copy-pastable.
I've added some empty lines so as to improve readability and group commands.
> Readme improvements (build instructions mostly)

- README.md
This adds a troubleshooting section to the main README file.
This should resolve #17 and #28.
> Adding a troubleshooting section with previously raised questions.

- ur_robot_driver/package.xml
Noticed it when I was looking at the `ur_robot_driver` wiki page.
> robot_driver: update tracker and repo urls.

- ur_dashboard_msgs/package.xml
> dashboard_msgs: fix typo in manifest description

- ur_robot_driver/src/ros/dashboard_client_ros.cpp
This PR fixes the duplicated assignments to a same ROS service server object.
> fixed duplicated service advertisements

- ur_robot_driver/config/ur10_controllers.yaml
- ur_robot_driver/config/ur10e_controllers.yaml
- ur_robot_driver/config/ur3_controllers.yaml
- ur_robot_driver/config/ur3e_controllers.yaml
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/config/ur5e_controllers.yaml
Almost like a named constant, but in yaml.
> config: use yaml anchor to reduce magic nrs

- README.md
I almost posted an issue about this problem too, so I suggest noting in the documentation. I didn't expect it to be this easy, and it's probably worth pointing it out.
> Add solution to troubleshooting

- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/include/ur_robot_driver/ur/ur_driver.h
- ur_robot_driver/src/ros/hardware_interface.cpp
- ur_robot_driver/src/ur/ur_driver.cpp
Added two parameters for servoj_gain and servoj_lookahead_time
> Parameterising gains

- ur_calibration/src/calibration_correction.cpp
> catch all exceptions to bring them to output.

- README.md
> Added a troubleshooting section about Nvidia drivers

- README.md
> readme: fix typo in build instructions

- ur_robot_driver/src/comm/server.cpp
As suggested inside #112 and #133
> Initialize address length for accept() call

- .travis.yml
- ur_dashboard_msgs/CMakeLists.txt
- ur_dashboard_msgs/package.xml
- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/package.xml
Builds ontop of #123 
This should
- Use `catkin_lint` in the ci pipeline
- Fix all package dependencies
> Fix package dependencies

- README.md
> Improve the quick start guide to make the start order more clear.

- controller_stopper/README.md
- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/launch/ur_control.launch
- ur_robot_driver/src/ros/hardware_interface.cpp
As proposed inside #155 
This is currently a draft as I noticed that documentation in the code and the resulting docfile have diverged, probably due to manual additions to the docfile instead of the code and me not realizing it during MR review.
> Use section commands for each individual topic/service/parameter url

- README.md
As raised inside #180 the wording was misleading there
> Clarified the requirement for using my fork of the universal_robot repo

- README.md
- ur_robot_driver/README.md
This MR aims at collecting a couple of documentation improvements.
Closes #140 
Closes #38  
Closes #51
> Improve documentation

- README.md
> Minor clarifications in the "auto-update calibration data" faq entry

- .github/workflows/ci.yml
- ur_robot_driver/scripts/check_urls.sh
- ur_robot_driver/src/ur/calibration_checker.cpp
The output was generated when we didn't have the final repository available.
However, updating the output got lost over time...
> Add actual documentation link into calibration checker output

- README.md
As this came up in #191 and #195 we decided to add this to the troubleshooting section.
> Added a section about EtherNet/IP incompatibility

- ur_robot_driver/resources/ros_control.urscript
Addresses https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/96 as a part of WRID2020.
> Prefixing "ExternalControl: " to log messages

- README.md
- ur_robot_driver/config/ur10_controllers.yaml
- ur_robot_driver/config/ur10e_controllers.yaml
- ur_robot_driver/config/ur3_controllers.yaml
- ur_robot_driver/config/ur3e_controllers.yaml
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/config/ur5e_controllers.yaml
- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/launch/ur10_bringup.launch
- ur_robot_driver/launch/ur10e_bringup.launch
- ur_robot_driver/launch/ur3_bringup.launch
- ur_robot_driver/launch/ur3e_bringup.launch
- ur_robot_driver/launch/ur5_bringup.launch
- ur_robot_driver/launch/ur5e_bringup.launch
- ur_robot_driver/launch/ur_common.launch
- ur_robot_driver/launch/ur_control.launch
> Renamed *_traj_controllers to *_joint_traj_controller

- README.md
As the library is now released, I adapted the README accordingly.
@stefanscherzinger please review
> Update the README regarding the availability of the ur_client_library availability

- .ci.rosinstall
- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/README.md
- ur_robot_driver/config/ur10_controllers.yaml
- ur_robot_driver/config/ur10e_controllers.yaml
- ur_robot_driver/config/ur16e_controllers.yaml
- ur_robot_driver/config/ur3_controllers.yaml
- ur_robot_driver/config/ur3e_controllers.yaml
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/config/ur5e_controllers.yaml
- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/launch/ur_control.launch
- ur_robot_driver/package.xml
- ur_robot_driver/resources/ros_control.urscript
- ur_robot_driver/resources/rtde_output_recipe.txt
- ur_robot_driver/src/hardware_interface.cpp
Pipeline will currently fail, as dependencies cannot be automatically installed.
> Beta testing

- README.md
Make sure that users know it's a beta version. Also provide an easy start and show them where to file issues.
Additional things we should add:
- Link to the respective UR forum
- Give users a way of simple (non-issue-tracking) feedback, e.g. with a poll or similar.
> Add beta testing remark and intro to top-level readme

- README.md
Now we are ready for the official beta release.
Ready, Set, Go testing!
> Adding link to the Survey for beta feedback

- ur_robot_driver/config/ur3e_controllers.yaml
This fixes #336
Thanks to @gavanderhoorn @bblumberg
> Fix yaml file for UR3e robots

- README.md
WIP: Let's put that in once beta testing has started.
> Notify of beta testing in top-level readme

- ur_robot_driver/doc/features.md
Added the feature "headless mode" to the feature list.
> Added headless mode to the feature list

- ur_robot_driver/launch/ur_control.launch
as the pull request https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/88/files
added the parameter to set servoj_gain and servoj_lookahead_time, add these parameters also in the launch file.
> add arg for servoj_gain servoj_lookahead_time in ur_control.launch

- README.md
As this question was risen [in the UR forum](https://discourse.ros.org/t/universal-robots-ros-driver-is-ready-for-beta-feedback/19466/2), let's put that to the troubleshooting section.
> Added short notice about MoveIt! and Cartesian controllers

- ur_robot_driver/doc/ROS_INTERFACE.md
- ur_robot_driver/launch/ur_control.launch
This is part of https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/31
> Use urscript file from client library by default

- ur_robot_driver/launch/ur10_bringup.launch
- ur_robot_driver/launch/ur10e_bringup.launch
- ur_robot_driver/launch/ur16e_bringup.launch
- ur_robot_driver/launch/ur3_bringup.launch
- ur_robot_driver/launch/ur3e_bringup.launch
- ur_robot_driver/launch/ur5_bringup.launch
- ur_robot_driver/launch/ur5e_bringup.launch
- ur_robot_driver/launch/ur_common.launch
- ur_robot_driver/launch/ur_control.launch
- ur_robot_driver/src/hardware_interface.cpp
> Reverse ip

- ur_robot_driver/src/hardware_interface.cpp
Mandatory check in the client library has been deprecated.
This uses the changes introduced in https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/65
This should be merged after ur_client_library has been binary-released with this change.
> Call calibration check in ROS driver

- README.md
- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/config/ur10_controllers.yaml
- ur_robot_driver/config/ur10e_controllers.yaml
- ur_robot_driver/config/ur16e_controllers.yaml
- ur_robot_driver/config/ur3_controllers.yaml
- ur_robot_driver/config/ur3e_controllers.yaml
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/config/ur5e_controllers.yaml
- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/launch/ur10_bringup.launch
- ur_robot_driver/launch/ur10e_bringup.launch
- ur_robot_driver/launch/ur16e_bringup.launch
- ur_robot_driver/launch/ur3_bringup.launch
- ur_robot_driver/launch/ur3e_bringup.launch
- ur_robot_driver/launch/ur5_bringup.launch
- ur_robot_driver/launch/ur5e_bringup.launch
- ur_robot_driver/launch/ur_common.launch
- ur_robot_driver/launch/ur_control.launch
- ur_robot_driver/package.xml
- ur_robot_driver/resources/rtde_output_recipe.txt
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/test/driver.test
- ur_robot_driver/test/integration_test.py
Adds the trajectory interface from the [beta-testing](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/beta-testing) branch.
There are a couple of things still missing (e.g. proper documentation, config- and launchfile integration)
> Trajectory interface

- controller_stopper/LICENSE
- controller_stopper/include/controller_stopper/controller_stopper.h
- controller_stopper/src/controller_stopper.cpp
- controller_stopper/src/controller_stopper_node.cpp
- ur_calibration/LICENSE
- ur_calibration/include/ur_calibration/calibration.h
- ur_calibration/include/ur_calibration/calibration_consumer.h
- ur_calibration/src/calibration.cpp
- ur_calibration/src/calibration_consumer.cpp
- ur_calibration/src/calibration_correction.cpp
- ur_calibration/test/calibration_test.cpp
- ur_robot_driver/LICENSE
- ur_robot_driver/include/ur_robot_driver/dashboard_client_ros.h
- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/include/ur_robot_driver/robot_state_helper.h
- ur_robot_driver/src/dashboard_client_node.cpp
- ur_robot_driver/src/dashboard_client_ros.cpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/src/hardware_interface_node.cpp
- ur_robot_driver/src/robot_state_helper.cpp
- ur_robot_driver/src/robot_state_helper_node.cpp
Removed copyright notice from LICENSE file, as the license file itself isn't
copyrighted by FZI
> Added "On behalf of Universal Robots A/S" notice

- README.md
We moved all features from beta-testing to the staging branch.
> Moved beta notice to staging branch

- ur_robot_driver/doc/features.md
Update the feature list with the new features from this branch
> Update feature list

- README.md
ur_msgs has been released to noetic
> Removed noetic build notice on ur_msgs

- ur_robot_driver/launch/ur_control.launch
As mentioned in #206 this lists a non-existing controller
> Fix default controller in common launchfile

- ur_robot_driver/scripts/tool_communication
That file was missing a license header.
> Add missing license header to tool_communication

- ur_robot_driver/doc/controllers.md
- ur_robot_driver/doc/features.md
This PR adds more documentation for the changes currently introduced in the staging branch.
> Add more documentation to new features

- controller_stopper/CHANGELOG.rst
- controller_stopper/package.xml
- ur_calibration/CHANGELOG.rst
- ur_calibration/package.xml
- ur_dashboard_msgs/CHANGELOG.rst
- ur_dashboard_msgs/package.xml
- ur_robot_driver/CHANGELOG.rst
- ur_robot_driver/package.xml
Prepare release with proper changelog and version numbers
> Prepare release v2.0.0

- .github/workflows/ci.yml
This PR does two things: It schedules a pipeline run each day and it allows the runs using the [testing] repo to fail.
> Schedule ci

- controller_stopper/package.xml
- ur_calibration/package.xml
- ur_dashboard_msgs/package.xml
> Remove boilerplate comments from package.xml files

- LICENSE
- ur_dashboard_msgs/LICENSE
As suggested in https://github.com/ros/rosdistro/pull/35593#discussion_r1044750667
> Add license file at root and in msgs package

- ur_robot_driver/src/hardware_interface.cpp
This was producing a -Wreorder when compiling
> Change initializer list ordering to match declaration in header file

- ur_robot_driver/CMakeLists.txt
See https://github.com/ros/catkin/pull/1052 for details
> Bump required cmake version to fix the CMake warning about CMP0048

- ur_calibration/CMakeLists.txt
- ur_dashboard_msgs/CMakeLists.txt
> Bump cmake minimum version for all packages in repo

- README.md
- ur_robot_driver/config/ur30_controllers.yaml
- ur_robot_driver/launch/ur30_bringup.launch
Related to [#674](https://github.com/ros-industrial/universal_robot/pull/674)
> Added support for UR30

- README.md
Align the documented required Robot SW version to the same as the current version of the client library
> Update robot SW requirements

- ur_calibration/src/calibration.cpp
- ur_calibration/test/calibration_test.cpp
It seems that for certain robots the calibration extraction and correction fails. This PR fixes this.
Note: This is a ROS 1 backport of https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/1017
> Fix calibration

- .github/workflows/ci_format.yml
- .github/workflows/reusable_ici.yml
> CI: Update actions

- .noetic.rosinstall
- README.md
Since a while we moved to a `noetic-devel` branch on the support repo.
> Update branch of support repo for noetic

- ur_calibration/package.xml
- ur_dashboard_msgs/package.xml
- ur_robot_driver/package.xml
This commit updates the package maintainers as the project's governance has changed a bit.
> Update package maintainers

- .github/dependabot.yml
This dependabot configuration will open PRs with github action updates when available.
> Add dependabot.yml to update github actions

- ur_robot_driver/launch/ur12e_bringup.launch
- ur_robot_driver/launch/ur7e_bringup.launch
This has been forgotten in #742
> Add launchfiles for ur7e and ur12e
